export const WORKDATA = [
  {
    company: "Arnawa Digital",
    href: "",
    location: "Remote",
    title: "Founder",
    logoUrl: "/arnawa_digital_logo.png",
    start: "April 2023",
    end: "Now",
    description:
      "My Design & Development Service Agency. Available services are Graphic Design, UI/UX Design, Product Design, Website Development, Mobile Apps Development, Branding, and Social Media Management.",
    milestones: ["Lorem ipsum dolor si amet", "Lorem ipsum dolor si amet 2"],
  },
  {
    company: "School Tech Indonesia",
    href: "",
    location: "Remote",
    title: "Frontend Developer",
    logoUrl: "/school_tech_logo.jpg",
    start: "August 2024",
    end: "Now",
    description:
      "Leading End-to-End Solution for School Management or technology solution provider that is changing the face of education through digital innovation with products in the form of applications or software as a service.",
    milestones: ["Lorem ipsum dolor si amet", "Lorem ipsum dolor si amet 2"],
  },
  // {
  //   company: "Next Gen Developer",
  //   href: "https://shopify.com",
  //   location: "Remote",
  //   title: "Web Developer - Project Based Internship",
  //   logoUrl: "/profile.jpg",
  //   start: "January 2024",
  //   end: "April 2024",
  //   description: "",
  // },
  {
    company: "Informatics Laboratory",
    href: "",
    location: "On Site",
    title: "Programming Algorithm Practicum Assistant",
    logoUrl: "/informatics_lab_logo.jpg",
    start: "September 2022",
    end: "Juny 2023",
    description:
      "IT laboratory of Telkom University that works to facilitate students to improve their IT skills and also to teach selected students to educate and manage lower level students in certain courses.",
    milestones: ["Lorem ipsum dolor si amet", "Lorem ipsum dolor si amet 2"],
  },
  {
    company: "Rainbow Kids Bandung",
    href: "",
    location: "On Site",
    title: "Part Time English and Math Teacher",
    logoUrl: "/rainbow_kids_logo.png",
    start: "November 2022",
    end: "July 2023",
    description:
      "Company specialized in the field of education, especially private education that teaches each student a 1 on 1 level (On Site & Online). The scope of courses is widely from kindergarten to high school.",
    milestones: ["Lorem ipsum dolor si amet", "Lorem ipsum dolor si amet 2"],
  },
  {
    company: "Telkom University Education Movement",
    href: "",
    location: "On Site",
    title: "Design and Publication Team",
    logoUrl: "/team_logo.jpg",
    start: "October 2021",
    end: "August 2022",
    description:
      "A non-profit organization established by Telkom University that is specialized in educational assistance to the local community, digital education forum, self-development training, and other educational activities.",
    milestones: ["Lorem ipsum dolor si amet", "Lorem ipsum dolor si amet 2"],
  },
  // {
  //   company: "Menebarmanfaat.id",
  //   href: "https://shopify.com",
  //   location: "Remote",
  //   title: "Design and Motion Video Division",
  //   logoUrl: "/profile.jpg",
  //   start: "November 2021",
  //   end: "March 2022",
  //   description: "",
  // },
];
